export const Actions = {
    SET_LOGGED_USER:"SET_LOGGED_USER",
    SET_SELECTED_USER:"SET_SELECTED_USER",
    SET_LOADING:"SET_LOADING",
    CLEAR_CONVERSATION:"CLEAR_CONVERSATION",
    SET_CONVERSATION:"SET_CONVERSATION",
    PUSH_TO_CONVERSATION:"PUSH_TO_CONVERSATION",
    SET_CONFIG:"SET_CONFIG",
}