export const Actions = {
    SET_LOGGED_USER:"SET_LOGGED_USER",
    SET_SELECTED_USER:"SET_SELECTED_USER",
    SET_LOADING:"SET_LOADING",
    SET_CONVERSATION_LIST:"SET_CONVERSATION_LIST",
    CLEAR_SELECTED_CONVERSATION:"CLEAR_SELECTED_CONVERSATION",
    SET_SELECTED_CONVERSATION:"SET_SELECTED_CONVERSATION",
    PUSH_TO_SELECTED_CONVERSATION:"PUSH_TO_SELECTED_CONVERSATION",
    SET_CONVERSATION_READ:"SET_CONVERSATION_READ",
    SET_CONFIG:"SET_CONFIG",
}